Fix/tuple not valid json (#6)
* use list for tuple

fixes https://github.com/sublimelsp/lsp-python-types/issues/4

* fix 'type' object is not subscriptable

Traceback (most recent call last):
  File "/Users/codetribe/Documents/github/lsp-python-types/generate.py", line 5, in <module>
    from utils.generate_enumerations import generate_enumerations
  File "/Users/codetribe/Documents/github/lsp-python-types/utils/generate_enumerations.py", line 4, in <module>
    from utils.helpers import capitalize, format_comment, indentation
  File "/Users/codetribe/Documents/github/lsp-python-types/utils/helpers.py", line 21, in <module>
    new_literal_structures: list[str] = []
TypeError: 'type' object is not subscriptable

* generate 3.3 types

* remove tuple import

* remove duplicates from the list

* Revert "remove duplicates from the list"

This reverts commit 689eaf0b026b29fb66d96f49e7bf52643ab0a533.

to fix this error:
/home/runner/work/lsp-python-types/lsp-python-types/lsp_types.py:4127:28 - error: Union requires two or more type arguments

Co-authored-by: Predrag Nikolic <predrag.nikolic@codetri.be>